### ISSUE TITLE
malformed input...

### ISSUE THREAD

**Issue by LeonardoPRO** [ManuelSch/sass-scss-converter#11]
Hello, Manuel!
**Your application is fantastic and one of the most correct in converting from sass to scss!
Thank you very much for your work!**

However, when you enter a line like this:
`@import ../../../node_modules/normalize.css/normalize`

instead of the expected string:
`@import "../../../node_modules/normalize.css/normalize";`

as a result, we get this:
`malformed input...`

approximately the same thing happens if somewhere inside there is a space an empty character (here, for example, it is after .2s):
```
$trs32: ease-in-out .32s
$trs2: ease-in-out .2s 
$basecolor: #25549
$activecolor: #1f477f
```

Thank you for your time!
Regards, Sergio

**Comment by ManuelSch** [comment]
Thanks for your report.

I'll take a look at the issue and keep you updated. In the meantime, feel free to open a pull request in case you'd like to add your own quick fix.

**Comment by ManuelSch** [comment]
So I finally got to look into this problem and I have good and bad news for you:

The bad news is that I could not fix the error caused by quote-less `@import` statements in SASS. My solution mainly works by converting the input string into an AST via [sast](https://github.com/shawnbot/sast) (which internally uses [gonzales-pe](https://github.com/tonyganch/gonzales-pe)) and applying some custom fixes on the individual nodes before converting it back to a string. The problem with the quote-less `@import`s is that gonzales itself considers them malformed, so the only way I could fix this issue is by transforming them myself before the parsing step, which is a path I don't really want to take. So for now, this problem remains unfixed.

The good news is that I fixed the trailing spaces problem, so this should work now:
```
$trs32: ease-in-out .32s
$trs2: ease-in-out .2s 
$basecolor: #25549
$activecolor: #1f477f
```
